"""Small iptables/association fixtures; no network connections or workloads."""
from copy import deepcopy
from unittest import TestCase
from unittest.mock import Mock, patch

from tools.optimization_evidence.common import EvidenceError
from tools.optimization_kubernetes import evidence, proxy

SERVICE = "KUBE-SVC-" + "A" * 16
ENDPOINT = "KUBE-SEP-" + "B" * 16
LABEL = "unit-run/p0-g0-s0:grpc"


def graph():
    return {"namespace": "unit-run", "targets": [{"service_name": "p0-g0-s0", "service_uid": "service-uid",
        "cluster_ip": "10.96.1.2", "pod_uid": "pod-uid", "pod_ip": "10.244.1.2"}]}


def tables():
    nat = f'''# Generated by iptables-save v1.8.11 (nf_tables)
*nat
:PREROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:KUBE-SERVICES - [0:0]
:KUBE-MARK-MASQ - [0:0]
:{SERVICE} - [0:0]
:{ENDPOINT} - [0:0]
-A PREROUTING -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A KUBE-SERVICES -d 10.96.1.2/32 -p tcp -m comment --comment "{LABEL} cluster IP" -m tcp --dport 7070 -j {SERVICE}
-A {SERVICE} ! -s 10.244.0.0/16 -d 10.96.1.2/32 -p tcp -m comment --comment "{LABEL} cluster IP" -m tcp --dport 7070 -j KUBE-MARK-MASQ
-A {SERVICE} -m comment --comment "{LABEL} -> 10.244.1.2:7070" -j {ENDPOINT}
-A {ENDPOINT} -s 10.244.1.2/32 -m comment --comment "{LABEL}" -j KUBE-MARK-MASQ
-A {ENDPOINT} -p tcp -m comment --comment "{LABEL}" -m tcp -j DNAT --to-destination 10.244.1.2:7070
COMMIT
# Completed
'''.encode()
    filtered = b"*filter\n:FORWARD ACCEPT [0:0]\n:KUBE-SERVICES - [0:0]\nCOMMIT\n"
    return nat, filtered


def missing(nat):
    return b"\n".join(line for line in nat.splitlines() if not line.startswith(b"-A KUBE-SERVICES ")) + b"\n"


class ProxyTests(TestCase):
    def test_exact_observed_kind_rule_shape_binds_service_and_pod(self):
        result = proxy.validate(*tables(), graph())
        self.assertTrue(result["ready"])
        self.assertEqual(result["routes"], [{**graph()["targets"][0], "service_chain": SERVICE,
            "endpoint_chain": ENDPOINT, "ready": True, "reason": None}])

    def test_absent_rule_and_hook_are_unavailable_not_connectivity_proofs(self):
        nat, filtered = tables()
        for value, reason in ((missing(nat), "service-route-missing-or-ambiguous"),
            (nat.replace(b"-A PREROUTING ", b"-A OUTPUT "), "service-portal-hook-not-programmed")):
            result = proxy.validate(value, filtered, graph())
            self.assertFalse(result["ready"])
            self.assertEqual(result["routes"][0]["reason"], reason)

    def test_wrong_or_multiple_dnat_and_extra_endpoint_matches_reject(self):
        nat, filtered = tables()
        duplicate = next(line for line in nat.splitlines() if b"-j DNAT" in line)
        cases = [nat.replace(b"--to-destination 10.244.1.2:7070", b"--to-destination 10.244.1.3:7070"),
                 nat.replace(b"COMMIT", duplicate + b"\nCOMMIT"),
                 nat.replace(b"-j DNAT", b"-s 10.244.1.9/32 -j DNAT")]
        for value in cases:
            with self.subTest(value=value):
                self.assertFalse(proxy.validate(value, filtered, graph())["ready"])

    def test_multiple_endpoint_selection_or_wrong_service_comment_is_not_ready(self):
        nat, filtered = tables()
        selection = next(line for line in nat.splitlines() if b" -> " in line)
        for value in (nat.replace(b"COMMIT", selection + b"\nCOMMIT"),
                      nat.replace(LABEL.encode(), b"foreign-run/p0-g0-s0:grpc")):
            self.assertFalse(proxy.validate(value, filtered, graph())["ready"])

    def test_only_rejects_matching_current_service_are_relevant(self):
        nat, filtered = tables()
        reject = b'-A KUBE-SERVICES -d 10.96.1.2/32 -p tcp -m comment --comment "no endpoints" -m tcp --dport 7070 -j REJECT --reject-with icmp-port-unreachable\n'
        for rule, ready in ((reject, False), (reject.replace(b"10.96.1.2", b"10.96.1.3"), True),
                            (reject.replace(b"--dport 7070", b"--dport 7071"), True)):
            self.assertEqual(proxy.validate(nat, filtered.replace(b"COMMIT", rule + b"COMMIT"), graph())["ready"], ready)

    def test_extra_unreachable_or_conditional_endpoint_selection_does_not_pass(self):
        nat, filtered = tables()
        value = nat.replace(b' -j ' + ENDPOINT.encode() + b'\n',
                            b' -m statistic --mode random --probability 0.5 -j ' + ENDPOINT.encode() + b'\n')
        self.assertFalse(proxy.validate(value, filtered, graph())["ready"])

    def test_table_framing_and_finite_bounds(self):
        nat, filtered = tables()
        for value in (nat.replace(b"COMMIT", b""), nat + nat, b"*mangle\nCOMMIT\n",
                      b"#" * (proxy.MAX_BYTES + 1), b"\n" * (proxy.MAX_LINES + 1)):
            with self.subTest(value=value[:40]):
                with self.assertRaises((EvidenceError, ValueError)):
                    proxy.validate(value, filtered, graph())

    def test_first_ready_stops_polling_without_a_network_operation(self):
        nat, filtered = tables()
        worker, progress = Mock(), Mock()
        worker.command.side_effect = [(missing(nat), 1), (filtered, 2), (nat, 3), (filtered, 4)]
        with patch.object(proxy.time, "monotonic_ns", return_value=10), patch.object(proxy, "stamp", return_value="11"), \
                patch.object(proxy.time, "sleep") as sleep:
            result = proxy.wait(worker, graph(), deadline=100, progress=progress)
        self.assertEqual(len(result["attempts"]), 2)
        self.assertEqual([call.args[0] for call in worker.command.call_args_list],
                         [proxy.COMMANDS["nat"], proxy.COMMANDS["filter"]] * 2)
        self.assertEqual(progress.call_count, 2)
        sleep.assert_called_once_with(0.1)

    def test_attempt_and_elapsed_bounds_retain_nonready_evidence(self):
        nat, filtered = tables()
        worker, progress = Mock(), Mock()
        worker.command.side_effect = [(missing(nat), 1), (filtered, 2)] * proxy.MAX_ATTEMPTS
        with patch.object(proxy.time, "monotonic_ns", return_value=10), patch.object(proxy, "stamp", return_value="11"), \
                patch.object(proxy.time, "sleep"):
            with self.assertRaises(TimeoutError):
                proxy.wait(worker, graph(), deadline=100, progress=progress)
        self.assertEqual(progress.call_count, proxy.MAX_ATTEMPTS)
        with patch.object(proxy.time, "monotonic_ns", return_value=10):
            with self.assertRaises(EvidenceError):
                proxy.wait(worker, graph(), deadline=10, progress=progress)


class ProxyReplayTests(TestCase):
    def fixture(self):
        nat, filtered = tables()
        replay = object.__new__(evidence.Replay)
        rows = {1: {"started_nanos": "11", "finished_nanos": "12", "stdout": nat},
                2: {"started_nanos": "13", "finished_nanos": "14", "stdout": filtered}}
        replay.command = Mock(side_effect=lambda index, argv: rows[index])
        parent = {"graph_ready_nanos": "10", "proxy_ready_nanos": "16", "finished_nanos": "30",
            "proxy_attempts": [{"nat_call": 1, "filter_call": 2, "observed_nanos": "15",
                                 "result": proxy.validate(nat, filtered, graph())}]}
        return replay, parent, rows

    def test_original_worker_rules_are_replayed_with_exact_commands(self):
        replay, parent, _ = self.fixture()
        self.assertEqual(replay.proxy_ready(parent, graph()), 16)
        self.assertEqual([call.args for call in replay.command.call_args_list],
                         [(1, proxy.COMMANDS["nat"]), (2, proxy.COMMANDS["filter"])])

    def test_changed_result_rules_clock_and_reused_call_reject(self):
        for change in ("result", "rule", "clock", "call"):
            replay, parent, rows = self.fixture()
            if change == "result":
                parent["proxy_attempts"][0]["result"]["routes"][0]["pod_uid"] = "changed"
            elif change == "rule":
                rows[1]["stdout"] = missing(rows[1]["stdout"])
            elif change == "clock":
                parent["proxy_ready_nanos"] = "12"
            else:
                parent["proxy_attempts"][0]["filter_call"] = 1
            with self.subTest(change=change), self.assertRaises(EvidenceError):
                replay.proxy_ready(parent, graph())

    def test_qualified_replay_rejects_continuing_after_first_ready(self):
        replay, parent, rows = self.fixture()
        parent["proxy_attempts"].append(deepcopy(parent["proxy_attempts"][0]))
        with self.assertRaisesRegex(EvidenceError, "first-ready"):
            replay.proxy_ready(parent, graph())
