/* Private bounded Java/C transport; canonical ABI is generated by wit-bindgen. */
#ifndef LSF_JAVA_BRIDGE_H
#define LSF_JAVA_BRIDGE_H
#include "probe.h"
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#define LSF_MAX_BYTES (8u * 1024u * 1024u)
#define LSF_MAX_ITEMS 65536u
typedef struct { uint8_t *data; size_t length, cursor, capacity; } lsf_wire;
static void lsf_require(bool condition) { if (!condition) __builtin_trap(); }
static void lsf_zero(void *value, size_t size) {
    volatile uint8_t *bytes = value;
    while (size--) *bytes++ = 0;
}
static void lsf_release(void *value, size_t size) { if (value) { lsf_zero(value, size); free(value); } }
static void *lsf_allocate(size_t count, size_t size) {
    lsf_require(size && count <= LSF_MAX_BYTES / size);
    void *value = calloc(count ? count : 1, size);
    lsf_require(value != NULL); return value;
}
static uint64_t lsf_get(lsf_wire *wire, size_t width) {
    lsf_require(width <= 8 && wire->cursor <= wire->length && width <= wire->length - wire->cursor);
    uint64_t value = 0;
    for (size_t i = 0; i < width; i++) value |= (uint64_t)wire->data[wire->cursor++] << (i * 8);
    return value;
}
static size_t lsf_count(lsf_wire *wire) { size_t value = (size_t)lsf_get(wire, 4); lsf_require(value <= LSF_MAX_ITEMS); return value; }
static void lsf_put(lsf_wire *wire, uint64_t value, size_t width) {
    lsf_require(width <= 8 && width <= LSF_MAX_BYTES - wire->length);
    if (width > wire->capacity - wire->length) {
        size_t capacity = wire->capacity ? wire->capacity * 2 : 128;
        if (capacity > LSF_MAX_BYTES) capacity = LSF_MAX_BYTES;
        uint8_t *next = lsf_allocate(capacity, 1);
        memcpy(next, wire->data, wire->length);
        lsf_release(wire->data, wire->capacity);
        wire->data = next; wire->capacity = capacity;
    }
    for (size_t i = 0; i < width; i++) wire->data[wire->length++] = (uint8_t)(value >> (i * 8));
}
static void lsf_finish(lsf_wire *wire) { lsf_require(wire->cursor == wire->length); }
static void lsf_dispose(lsf_wire *wire) { lsf_release(wire->data, wire->capacity); *wire = (lsf_wire){0}; }
void *lsf_java_alloc(int32_t length) {
    lsf_require(length >= 0 && (uint32_t)length <= LSF_MAX_BYTES);
    /* The payload bound excludes this private four-byte frame header. */
    uint8_t *data = calloc((size_t)length + 4, 1);
    lsf_require(data != NULL);
    uint32_t size = (uint32_t)length; memcpy(data, &size, 4); return data;
}
void lsf_java_free(void *pointer) {
    if (pointer) { uint32_t size; memcpy(&size, pointer, 4); lsf_require(size <= LSF_MAX_BYTES); lsf_release(pointer, size + 4); }
}
static void *lsf_result(lsf_wire *wire) {
    void *result = lsf_java_alloc((int32_t)wire->length);
    memcpy((uint8_t *)result + 4, wire->data, wire->length); lsf_dispose(wire); return result;
}
extern int main(int argc, char **argv);
extern void *lsf_java_dispatch(int32_t operation, void *data, int32_t length);
static bool lsf_initialized;
static lsf_wire lsf_invoke(int32_t operation, lsf_wire *arguments, void **owned) {
    if (!lsf_initialized) { lsf_initialized = true; lsf_require(main(0, NULL) == 0); }
    *owned = lsf_java_dispatch(operation, arguments->data, (int32_t)arguments->length);
    lsf_dispose(arguments);
    uint32_t size; memcpy(&size, *owned, 4); lsf_require(size <= LSF_MAX_BYTES);
    return (lsf_wire){(uint8_t *)*owned + 4, size, 0, size};
}
#endif
