// Generated by tools/generate_transaction_contracts.py; do not edit.
pub const PROFILE: &str = "lsf-transaction-v1";
pub const HOST_ABI_DIGEST: &str =
    "sha256:3b85f790f85ab23d36e492d7bd4a04a1b8aab87fc6f67dd7d7498bcf28129d35";
pub const PREPARATION_PROFILE_DIGEST: &str =
    "sha256:6acd7a248633dd01c9cdcbf8a1ed33fc5e6aa1d2edb09b7d89e53fda594b5507";
