// Disposable qualification only. Organization keys/configuration are never generated by the runtime image.
import assert from 'node:assert/strict';
import {readFile, writeFile, readdir, mkdir} from 'node:fs/promises';
import {randomBytes} from 'node:crypto';
import {qualify} from '../static-release/qualification.mjs';

assert.equal(process.getuid(), 10001);
await qualify('/native/bin/latent', '/work/frontend-inputs.json');
const candidates = (await readdir('/work')).filter(name => name.startsWith('lsf-frontend-'));
assert.equal(candidates.length, 1);
const work = '/work/' + candidates[0];
await writeFile('/config/policy.json', await readFile(work + '/policy.json'), {mode: 0o600, flag: 'wx'});
const token = randomBytes(32).toString('base64url');
const invokeToken = randomBytes(32).toString('base64url');
const node = {formatVersion: 1, securityProfile: 'local-experimental-v1', dataDirectory: '/var/lib/lsf',
  nodeId: 'container-qualification', bind: '127.0.0.1:50051', shutdownGraceMillis: 5000,
  supplyChain: {mode: 'enforced', policyFile: '/etc/lsf/policy.json', clockLeaseSeconds: 5},
  credentials: [{token, subject: 'container-operator', tenant: 'tests', role: 'operator'},
    {token: invokeToken, subject: 'container-invoker', tenant: 'tests', role: 'invoke'}],
  audit: {mode: 'durable'}, limits: {maximumPayloadBytes: 2097152},
  execution: {maximumWallTimeMillis: 10000},
  httpIngress: {formatVersion: 1, bind: '127.0.0.1:18080', transport: {mode: 'loopback'},
    authentication: {mode: 'public-origins', origins: [{authority: 'frontend.example.test', subject: 'frontend-browser', tenant: 'tests'}]},
    limits: {maximumConnections: 4, maximumExchanges: 2, maximumBufferBytes: 25165824, maximumRequestsPerConnection: 8,
      headerTimeoutMillis: 8000}}};
const client = {formatVersion: 1, defaultProfile: 'local', profiles: [{name: 'local',
  endpoint: 'http://127.0.0.1:50051', tenant: 'tests', token, connectTimeoutMillis: 500, rpcTimeoutMillis: 1000,
  limits: {maximumComponentBytes: 16777216, maximumPayloadBytes: 1048576, maximumResponseBytes: 262144}}]};
for (const [name, value] of [['node.json', node], ['client.json', client]]) {
  await writeFile('/config/' + name, JSON.stringify(value), {mode: 0o600, flag: 'wx'});
}
// CI holds no copy of this credential. The operator receiver reads the protected
// mount inside the node namespace; selection documents contain identities only.
await writeFile('/config/ci-client.json', JSON.stringify(client), {mode: 0o600, flag: 'wx'});
const invokeClient = structuredClone(client);
invokeClient.profiles[0].token = invokeToken;
await writeFile('/config/invoke-client.json', JSON.stringify(invokeClient), {mode: 0o600, flag: 'wx'});
await mkdir('/config/private', {mode: 0o700});
await writeFile('/config/private/native-aot.key', randomBytes(32), {mode: 0o600, flag: 'wx'});
const release = JSON.parse(await readFile('/native/release.json', 'utf8'));
const external = structuredClone(node);
external.securityProfile = 'external-capsule-v1';
external.isolatedAot = {compilerExecutable: '/opt/lsf/release/bin/latent-aot-compiler',
  compilerDigest: 'sha256:' + release.engine.compilerSha256, keyFile: '/etc/lsf/private/native-aot.key',
  blobRoot: '/var/cache/lsf/native-blobs', receiptRoot: '/var/cache/lsf/native-receipts'};
await writeFile('/config/external.json', JSON.stringify(external), {mode: 0o600, flag: 'wx'});
await writeFile('/work/current.json', JSON.stringify({work}), {mode: 0o600, flag: 'wx'});
console.log(JSON.stringify({prepared: true, actualReleasedCli: true, disposableTestIdentity: true}));
