//! Bounded OS entropy under the original activation's authority and ledger.
use super::{
    ActivationCapabilityBroker, CapabilityCallCost, CapabilityDispatch, CapabilitySession,
    ProviderBudgetRequirement, ProviderCall, ProviderConfiguration, ProviderReference,
    ProviderRegistration,
};
use latent_core::{BudgetDimension, PlatformError, PlatformErrorCode};
use latent_policy::capability::ResourceTarget;
use sha2::{Digest, Sha256};
use std::{future::Future, pin::Pin, sync::Arc};
use zeroize::Zeroizing;

mod entropy;
mod ownership;
mod statistics;
#[cfg(feature = "test-support")]
pub use entropy::TestEntropy;
pub use statistics::RandomSnapshot;

pub const RANDOM_CAPABILITY: &str = "latent:random/random@0.1.0";
pub const RANDOM_PROFILE: &str = "system-random-v1";
const BASE_FUEL: u64 = 100;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RandomLimits {
    pub maximum_bytes_per_call: usize,
    pub maximum_bytes_per_activation: usize,
}

impl Default for RandomLimits {
    fn default() -> Self {
        Self {
            maximum_bytes_per_call: 4096,
            maximum_bytes_per_activation: 65_536,
        }
    }
}
impl RandomLimits {
    fn validate(self) -> Result<(), PlatformError> {
        if !(8..=4096).contains(&self.maximum_bytes_per_call)
            || !(self.maximum_bytes_per_call..=65_536).contains(&self.maximum_bytes_per_activation)
        {
            return Err(super::invalid());
        }
        Ok(())
    }
}
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RandomError {
    InvalidLength,
    BudgetExhausted,
    Unavailable,
}
impl From<PlatformError> for RandomError {
    fn from(error: PlatformError) -> Self {
        match error.code {
            PlatformErrorCode::ResourceExhausted => Self::BudgetExhausted,
            _ => Self::Unavailable,
        }
    }
}
/// Data is wiped before the original call releases its output reservation.
/// No Debug implementation can accidentally disclose the generated bytes.
pub struct RandomCompletion {
    pub bytes: Zeroizing<Vec<u8>>,
    pub owner: ProviderCall,
}
pub type PendingRandom =
    Pin<Box<dyn Future<Output = Result<RandomCompletion, RandomError>> + Send>>;

/// One node-owned installation; no service-specific state, task or entropy fd.
pub struct RandomProvider {
    registration: ProviderRegistration,
    limits: RandomLimits,
    source: entropy::Source,
    statistics: statistics::Statistics,
}
impl RandomProvider {
    pub fn system(
        broker: &ActivationCapabilityBroker,
        epoch: u64,
        limits: RandomLimits,
    ) -> Result<Arc<Self>, PlatformError> {
        Self::install(broker, epoch, limits, entropy::Source::System)
    }
    #[cfg(feature = "test-support")]
    /// Explicit trusted test injection. Node configuration cannot select it.
    pub fn for_test(
        broker: &ActivationCapabilityBroker,
        epoch: u64,
        limits: RandomLimits,
        source: Arc<dyn TestEntropy>,
    ) -> Result<Arc<Self>, PlatformError> {
        Self::install(broker, epoch, limits, entropy::Source::Test(source))
    }
    fn install(
        broker: &ActivationCapabilityBroker,
        epoch: u64,
        limits: RandomLimits,
        source: entropy::Source,
    ) -> Result<Arc<Self>, PlatformError> {
        limits.validate()?;
        let mut identity = Sha256::new();
        identity.update(source.profile().as_bytes());
        identity.update((limits.maximum_bytes_per_call as u64).to_le_bytes());
        identity.update((limits.maximum_bytes_per_activation as u64).to_le_bytes());
        let digest = format!("sha256:{:x}", identity.finalize());
        let registration = broker.register_provider(ProviderConfiguration {
            capability: RANDOM_CAPABILITY,
            profile: source.profile(),
            configuration_digest: &digest,
            configuration_epoch: epoch,
            restriction_json: br#"{"operations":["bytes","u64-value"]}"#,
            minimum_call_charges: &[
                ProviderBudgetRequirement {
                    operation: "bytes",
                    dimension: BudgetDimension::CpuFuel,
                    minimum: BASE_FUEL,
                },
                ProviderBudgetRequirement {
                    operation: "u64-value",
                    dimension: BudgetDimension::CpuFuel,
                    minimum: BASE_FUEL + 8,
                },
            ],
        })?;
        Ok(Arc::new(Self {
            registration,
            limits,
            source,
            statistics: statistics::Statistics::default(),
        }))
    }
    #[must_use]
    pub fn reference(&self) -> ProviderReference {
        self.registration.reference()
    }
    pub fn retire(&self) {
        self.registration.retire();
    }
    #[must_use]
    pub fn snapshot(&self) -> RandomSnapshot {
        self.statistics.snapshot()
    }
    pub fn bytes(
        self: &Arc<Self>,
        session: &CapabilitySession,
        length: u32,
    ) -> Result<PendingRandom, RandomError> {
        self.start(session, "bytes", length as usize)
    }
    pub fn u64_value(
        self: &Arc<Self>,
        session: &CapabilitySession,
    ) -> Result<PendingRandom, RandomError> {
        self.start(session, "u64-value", 8)
    }
    fn start(
        self: &Arc<Self>,
        session: &CapabilitySession,
        operation: &str,
        length: usize,
    ) -> Result<PendingRandom, RandomError> {
        self.statistics.started(operation);
        let prepared = (|| {
            if length > self.limits.maximum_bytes_per_call {
                return Err(RandomError::InvalidLength);
            }
            if !session
                .uses_provider(&self.reference())
                .map_err(RandomError::from)?
            {
                return Err(RandomError::Unavailable);
            }
            let aggregate = ownership::Reservation::new(
                session,
                length,
                self.limits.maximum_bytes_per_activation,
            )?;
            let cost = CapabilityCallCost::new(length)
                .with_charge(BudgetDimension::CpuFuel, BASE_FUEL + length as u64)?;
            let input = (length as u64).to_le_bytes();
            let dispatch = session.prepare_owned_dispatch(
                RANDOM_CAPABILITY,
                operation,
                ResourceTarget::Random,
                &input,
                cost,
            )?;
            Ok((dispatch, aggregate))
        })();
        let (dispatch, aggregate) = prepared.inspect_err(|error| self.statistics.failed(*error))?;
        let provider = self.clone();
        Ok(Box::pin(async move {
            provider
                .generate(dispatch, aggregate, length)
                .await
                .inspect_err(|error| provider.statistics.failed(*error))
        }))
    }
    async fn generate(
        &self,
        dispatch: CapabilityDispatch,
        mut aggregate: ownership::Reservation,
        length: usize,
    ) -> Result<RandomCompletion, RandomError> {
        let mut call = dispatch.dispatch(|call| call).await?;
        call.require_host_mode()?;
        if !call.provider_matches(&self.reference()) {
            return Err(RandomError::Unavailable);
        }
        let mut bytes = Zeroizing::new(Vec::new());
        bytes
            .try_reserve_exact(length)
            .map_err(|_| RandomError::BudgetExhausted)?;
        bytes.resize(length, 0);
        call.check()?;
        aggregate.commit();
        let result = self.source.fill(&mut bytes);
        let outcome = if result.is_ok() {
            self.statistics.generated(length);
            latent_audit::AuditProviderOutcome::HostCompleted
        } else {
            latent_audit::AuditProviderOutcome::Rejected
        };
        call.record_provider_outcome(outcome)?;
        // Audit records contain only operation/resource class and requested length.
        call.finish_audit().await;
        result?;
        call.check()?;
        Ok(RandomCompletion { bytes, owner: call })
    }
}

#[cfg(test)]
mod tests {
    use super::RandomLimits;
    #[test]
    fn configured_limits_cannot_widen_hard_bounds_or_exclude_the_scalar_operation() {
        assert!(RandomLimits::default().validate().is_ok());
        for (call, activation) in [
            (0, 8),
            (7, 8),
            (4097, 8192),
            (8, 7),
            (8, 65_537),
            (usize::MAX, usize::MAX),
        ] {
            assert!(RandomLimits {
                maximum_bytes_per_call: call,
                maximum_bytes_per_activation: activation
            }
            .validate()
            .is_err());
        }
        assert!(RandomLimits {
            maximum_bytes_per_call: 8,
            maximum_bytes_per_activation: 8
        }
        .validate()
        .is_ok());
    }
}
