"""Build separate source-observed Java domain and ordinary HTTP adapter packages."""
from pathlib import Path
import json

from tools.java_capsule_build import build
from tools.java_capsule_project import create, validate
from tools.java_http_composition.revision import create_revision
from tools.java_http_generation.project import generate, check
from tools.java_http_generation.probes import qualify as qualify_generation
from tools.rust_capsule_project import ROOT, digest, read_json, snapshot, write_json

COMPOSITION_CPU_FUEL = 10_000_000_000
SPIN_CPU_FUEL = COMPOSITION_CPU_FUEL


def qualification_budget(project: Path, *, inherited=False) -> dict:
    """Capture a fresh fixture declaration before compilation and signing."""
    before = snapshot(project)
    descriptor, _, _ = validate(before)
    expected = COMPOSITION_CPU_FUEL if inherited else 1_000_000_000
    if descriptor["limits"]["cpuFuel"] != expected:
        raise ValueError("java-composition-default-cpu-budget-changed")
    previous = dict(descriptor["limits"])
    if not inherited:
        descriptor["limits"]["cpuFuel"] = COMPOSITION_CPU_FUEL
        (project / "capsule-project.json").write_text(json.dumps(descriptor, indent=2) + "\n", encoding="utf-8")
    after = snapshot(project)
    validate(after)
    if set(before) != set(after) or any(before[name] != after[name]
            for name in before if name != "capsule-project.json"):
        raise ValueError("java-composition-budget-changed-other-source")
    return {"beforeDescriptorDigest": digest(before["capsule-project.json"]),
        "afterDescriptorDigest": digest(after["capsule-project.json"]),
        "beforeLimits": previous, "afterLimits": descriptor["limits"],
        "signedExecutionQualified": False}


def projects(output: Path, *, tools: dict[str, Path] | None = None,
             generation_cases: Path | None = None,
             diagnostic_adaptations: dict | None = None) -> dict[str, Path]:
    result = {}
    budgets = {}
    for name in ("domain", "context-required"):
        project = create(output / name, "greeting", "java-http-" + name)
        fixture = ROOT / "examples/java-http-composition" / name
        (project / "src/dev/latent/app/Capsule.java").write_bytes((fixture / "Capsule.java").read_bytes())
        (project / "wit/world.wit").write_bytes((fixture / "world.wit").read_bytes())
        descriptor = read_json(project / "capsule-project.json")
        descriptor["world"] = "examples:java-http-" + name + "/service@1.0.0"
        descriptor["limits"].update(childCalls=4 if name == "adapter" else 0,
                                    memoryBytes=134217728 if name == "adapter" else 67108864)
        (project / "capsule-project.json").write_text(json.dumps(descriptor, indent=2) + "\n", encoding="utf-8")
        lock = read_json(project / "sdk-lock.json")
        lock["template"] = {"name": "java-http-" + name,
                            "sourceDigest": digest((fixture / "Capsule.java").read_bytes()),
                            "witDigest": digest((fixture / "world.wit").read_bytes())}
        (project / "sdk-lock.json").write_text(json.dumps(lock, indent=2) + "\n", encoding="utf-8")
        if name == "domain":
            budgets[name] = qualification_budget(project)
        result[name] = project

    if diagnostic_adaptations is not None:
        from tools.java_http_composition import provider_timeout
        diagnostic_adaptations["domain"] = provider_timeout.adapt_domain(result["domain"])

    selection = ROOT / "examples/java-http-composition/routes.json"
    selected_tools = {} if tools is None else {"tools": tools}
    result["adapter"] = generate(result["domain"], selection, output / "adapter", **selected_tools)
    check(result["domain"], selection, result["adapter"], **selected_tools)
    if generation_cases is not None:
        qualify_generation(result["domain"], selection, result["adapter"], generation_cases)
    # Generation carries the domain allowance; validate it without editing the generated bytes.
    budgets["adapter"] = qualification_budget(result["adapter"], inherited=True)
    result["adapter-next"] = create_revision(result["adapter"], output / "adapter-next")
    write_json(output / "qualification-budgets.json", {
        "schemaVersion": "latent.java-http.fixture-budgets.v1",
        "purpose": "bounded composed drain qualification", "captures": budgets,
        "candidateCpuFuel": read_json(result["adapter-next"] / "capsule-project.json")["limits"]["cpuFuel"],
        "generatorCheckedBeforeFixtureEdit": True,
        "generationNegativeCasesChecked": generation_cases is not None,
        "signedExecutionQualified": False})
    return result



def compile_pair(output: Path, wasi_sdk: Path, binaries: dict, *, diagnostics=False) -> dict[str, Path]:
    if type(diagnostics) is not bool:
        raise ValueError("Java diagnostic build selection must be explicit")
    adaptations = {} if diagnostics else None
    selected = projects(output / "projects", generation_cases=output / "generation-cases",
                        diagnostic_adaptations=adaptations)
    if diagnostics:
        from tools.java_http_composition import provider_timeout
        for name in ("adapter", "adapter-next"):
            adaptations[name] = provider_timeout.adapt_adapter(selected[name])
        write_json(output / "diagnostic-adaptations.json", adaptations)
    return {name: build(project, output / "builds" / name,
        binaries["examples/capsule_contracts"], binaries.get("examples/package"),

        "https://github.com/KirilsTurkins/latent-service-fabric", wasi_sdk)
        for name, project in selected.items()}
