"""Java source for the finite buffered-web/local-service composition profile."""
import json


def source(selection: dict, routes: list[dict]) -> bytes:
    cases = []
    for route in routes:
        # A switch per path can carry two methods without duplicate Java labels.
        if any(row["path"] == route["path"] for row in routes[:routes.index(route)]): continue
        choices = [row for row in routes if row["path"] == route["path"]]
        expression = "null"
        for row in reversed(choices):
            method = "Get" if row["method"] == "GET" else "Post"
            expression = "request.method() == LatentWebApplicationMethod." + method + " ? " + json.dumps(row["operation"]) + " : " + expression
        cases.append("            case " + json.dumps(route["path"]) + " -> " + expression + ";")
    domain = selection["domain"]
    text = '''// Generated by latent.java-http.adapter.v1; regenerate from WIT and explicit routes.
package dev.latent.app;
import dev.latent.generated.Bindings;
import dev.latent.generated.Bindings.*;
import dev.latent.guest.Option;
import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.List;

public final class Capsule implements Bindings.Exports {
    public LatentWebApplicationResponse handle(LatentWebApplicationRequest request) {
        String operation = switch (request.path()) {
@CASES@
            default -> null;
        };
        if (operation == null) return response(404, "route-not-selected".getBytes(StandardCharsets.UTF_8));
        byte[] input;
        try {
            input = request.method() == LatentWebApplicationMethod.Get ? "[]".getBytes(StandardCharsets.UTF_8)
                : Base64.getDecoder().decode(request.bodyBase64());
        } catch (IllegalArgumentException invalid) {
            return response(400, "malformed-body".getBytes(StandardCharsets.UTF_8));
        }
        var target = new LatentServiceInvokeTarget(Option.none(), @SERVICE@,
            @CONTRACT@, operation, Option.some(@ROUTE@));
        var result = LatentServiceInvoke.call(target, input,
            "application/vnd.latent.wit-values.v1+json",
            new LatentServiceInvokeCallOptions(Option.none(), (short) 0, Option.none(), List.of()));
        if (result.tag() == 0) return response(200, result.successValue().payload());
        if (result.tag() == 1) return response(422, result.declaredErrorValue().payload());
        return response(switch (result.platformFailureValue().code()) {
            case PermissionDenied, Unauthenticated -> 403;
            case InvalidArgument -> 400;
            case DeadlineExceeded -> 504;
            case ResourceExhausted, Unavailable, Cancelled -> 503;
            default -> 500;
        }, "child-platform-failure".getBytes(StandardCharsets.UTF_8));
    }
    private static LatentWebApplicationResponse response(int status, byte[] body) {
        return new LatentWebApplicationResponse(LatentWebApplicationProfile.BufferedV1, status,
            List.of(), Option.some("application/json"), Option.none(), Base64.getEncoder().encodeToString(body));
    }
}
'''
    return (text.replace("@CASES@", "\n".join(cases)).replace("@SERVICE@", json.dumps(domain["service"]))
            .replace("@CONTRACT@", json.dumps(domain["contract"])).replace("@ROUTE@", json.dumps(domain["route"]))).encode()


def wit(name: str) -> bytes:
    return ("package examples:" + name + "@1.0.0;\n\nworld service {\n"
        "    import latent:clock/monotonic@0.1.0;\n    import latent:clock/wall@0.1.0;\n"
        "    import latent:service/invoke@0.1.0;\n    export latent:web/application@0.1.0;\n}\n\n"
        "world runtime-support {\n    import latent:clock/monotonic@0.1.0;\n"
        "    import latent:clock/wall@0.1.0;\n}\n").encode()
