;; Type-only component: no executable guest code, imports, or external tools at test time.
;; Regenerate: wasm-tools parse types.wat -o types.wasm
(component
  (type $record-def (record (field "name" string) (field "count" u32)))
  (export $record "record" (type $record-def))
  (type $tuple (tuple bool s64))
  (export "tuple" (type $tuple))
  (type $variant-def (variant (case "empty") (case "number" u64)))
  (export $variant "variant" (type $variant-def))
  (type $enum (enum "red" "blue"))
  (export "enum" (type $enum))
  (type $flags (flags "read" "write" "admin"))
  (export "flags" (type $flags))
  (type $option-def (option string))
  (export $option "option" (type $option-def))
  (type $nested (option $option))
  (export "nested" (type $nested))
  (type $result-def (result string (error $variant)))
  (export $result "result" (type $result-def))
  (type $unit-result (result))
  (export "unit-result" (type $unit-result))
  (type $nested-result (list $result))
  (export "nested-result" (type $nested-result))
  (type $wide-def (record (field "a" $record) (field "b" $record) (field "c" $record)))
  (export $wide "wide" (type $wide-def))
  (type $list (list u8))
  (export "list" (type $list))
  (type $wide-list (list $wide))
  (export "wide-list" (type $wide-list))
)
