use super::RandomError;
use std::sync::atomic::{AtomicU64, Ordering};

/// Fixed numeric counters. Generated bytes may not have reached the guest.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct RandomSnapshot {
    pub bytes_calls: u64,
    pub u64_calls: u64,
    pub generated_bytes: u64,
    pub invalid_lengths: u64,
    pub budget_exhaustions: u64,
    pub unavailable: u64,
}
#[derive(Default)]
pub(super) struct Statistics {
    bytes_calls: AtomicU64,
    u64_calls: AtomicU64,
    generated_bytes: AtomicU64,
    invalid_lengths: AtomicU64,
    budget_exhaustions: AtomicU64,
    unavailable: AtomicU64,
}
fn add(counter: &AtomicU64, amount: u64) {
    let _ = counter.fetch_update(Ordering::Relaxed, Ordering::Relaxed, |old| {
        Some(old.saturating_add(amount))
    });
}
impl Statistics {
    pub(super) fn started(&self, operation: &str) {
        add(
            if operation == "bytes" {
                &self.bytes_calls
            } else {
                &self.u64_calls
            },
            1,
        );
    }
    pub(super) fn generated(&self, length: usize) {
        add(&self.generated_bytes, length as u64);
    }
    pub(super) fn failed(&self, error: RandomError) {
        add(
            match error {
                RandomError::InvalidLength => &self.invalid_lengths,
                RandomError::BudgetExhausted => &self.budget_exhaustions,
                RandomError::Unavailable => &self.unavailable,
            },
            1,
        );
    }
    pub(super) fn snapshot(&self) -> RandomSnapshot {
        RandomSnapshot {
            bytes_calls: self.bytes_calls.load(Ordering::Relaxed),
            u64_calls: self.u64_calls.load(Ordering::Relaxed),
            generated_bytes: self.generated_bytes.load(Ordering::Relaxed),
            invalid_lengths: self.invalid_lengths.load(Ordering::Relaxed),
            budget_exhaustions: self.budget_exhaustions.load(Ordering::Relaxed),
            unavailable: self.unavailable.load(Ordering::Relaxed),
        }
    }
}
