// Generated by `wit-bindgen` 0.62.0. DO NOT EDIT!
#include "clocks.h"
#include <stdlib.h>

// Imported Functions from `latent:clock/monotonic@0.1.0`

__attribute__((__import_module__("latent:clock/monotonic@0.1.0"), __import_name__("now-nanos")))
extern int64_t __wasm_import_latent_clock_monotonic_now_nanos(void);

// Imported Functions from `latent:clock/wall@0.1.0`

__attribute__((__import_module__("latent:clock/wall@0.1.0"), __import_name__("now-unix-millis")))
extern int64_t __wasm_import_latent_clock_wall_now_unix_millis(void);

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Component Adapters

uint64_t latent_clock_monotonic_now_nanos(void) {
  int64_t ret = __wasm_import_latent_clock_monotonic_now_nanos();
  return (uint64_t) (ret);
}

uint64_t latent_clock_wall_now_unix_millis(void) {
  int64_t ret = __wasm_import_latent_clock_wall_now_unix_millis();
  return (uint64_t) (ret);
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_clocks(void);
__attribute__((used))
void __component_type_object_force_link_clocks_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_clocks();
}
