// Generated by `wit-bindgen` 0.62.0. DO NOT EDIT!
#ifndef __BINDINGS_CLOCKS_H
#define __BINDINGS_CLOCKS_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

// Imported Functions from `latent:clock/monotonic@0.1.0`
extern uint64_t latent_clock_monotonic_now_nanos(void);

// Imported Functions from `latent:clock/wall@0.1.0`
extern uint64_t latent_clock_wall_now_unix_millis(void);

#ifdef __cplusplus
}
#endif
#endif
