package examples:java-http-adapter@1.0.0;

world service {
    import latent:clock/monotonic@0.1.0;
    import latent:clock/wall@0.1.0;
    import latent:service/invoke@0.1.0;
    export latent:web/application@0.1.0;
}

world runtime-support {
    import latent:clock/monotonic@0.1.0;
    import latent:clock/wall@0.1.0;
}
