"""Explicit editor/container scaffolding from an already authenticated Linux bundle."""
from __future__ import annotations

import json
import hashlib
import os
from pathlib import Path
import secrets
import time

from . import bundle, paths
from .common import encode, require

IMAGE = "ubuntu@sha256:008173c23f95b170204355c12626cb5a965d779a7e1283b09e9cffbb1bf33ca3"
CERTIFICATE_IMAGE = "python@sha256:4c2cf9917bd1cbacc5e9b07320025bdb7cdf2df7b0ceaccb55e9dd7e30987419"
SNAPSHOT = "20260924T120000Z"
PACKAGES = {"ca-certificates": "20260601~24.04.1", "git": "1:2.43.0-1ubuntu7.3",
            "openssh-client": "1:9.6p1-3ubuntu13.19"}


def dockerfile() -> str:
    packages = " ".join(name + "=" + version for name, version in sorted(PACKAGES.items()))
    return f"""# Generated by latent-dev after verifying the selected offline bundle.
FROM {CERTIFICATE_IMAGE} AS bootstrap-certificates
FROM {IMAGE}
ARG DEBIAN_FRONTEND=noninteractive
COPY --from=bootstrap-certificates /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
RUN apt-get update -qq --snapshot {SNAPSHOT} \\
    && apt-get install -y --no-install-recommends --snapshot {SNAPSHOT} {packages} \\
    && rm -rf /var/lib/apt/lists/*
RUN groupadd --gid 10001 latent-dev \\
    && useradd --uid 10001 --gid 10001 --create-home --shell /bin/bash latent-dev \\
    && chmod 0700 /home/latent-dev
COPY --chown=0:0 verified/ /opt/latent-dev/
COPY expected-files.sha256 /opt/latent-dev/expected-files.sha256
RUN cd /opt/latent-dev && sha256sum --check --strict expected-files.sha256 \\
    && find /opt/latent-dev -type d -exec chmod 0755 {{}} + \\
    && find /opt/latent-dev -type f -exec chmod 0644 {{}} + \\
    && chmod 0755 /opt/latent-dev/bin/latent-dev /opt/latent-dev/bin/latent-portable-test-host
ENV PATH=/opt/latent-dev/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV SSH_AUTH_SOCK=/dev/null
USER 10001:10001
WORKDIR /workspaces/project
CMD ["/bin/sleep", "infinity"]
"""


def configuration(nonce: str) -> dict:
    require(len(nonce) == 16 and all(c in "0123456789abcdef" for c in nonce), "devcontainer-owner-nonce")
    return {"name": "LSF capsule development", "build": {"dockerfile": "Dockerfile", "context": "."},
        "containerUser": "latent-dev", "remoteUser": "latent-dev", "updateRemoteUserUID": False,
        "workspaceMount": "source=${localWorkspaceFolder},target=/workspaces/project,type=bind",
        "workspaceFolder": "/workspaces/project", "shutdownAction": "stopContainer",
        "userEnvProbe": "none",
        "mounts": [f"source=lsf-dev-{nonce},target=/home/latent-dev,type=volume"],
        "runArgs": ["--init", "--cap-drop=ALL", "--security-opt=no-new-privileges", "--pids-limit=256",
                    "--memory=2g", "--cpus=2"],
        "containerEnv": {"SSH_AUTH_SOCK": "/dev/null", "GIT_CONFIG_GLOBAL": "/dev/null",
                         "GIT_CONFIG_SYSTEM": "/dev/null", "GIT_TERMINAL_PROMPT": "0"},
        "remoteEnv": {"SSH_AUTH_SOCK": "/dev/null"}, "forwardPorts": [],
        "customizations": {"vscode": {"settings": {"task.allowAutomaticTasks": "off"}}}}


def generate(project: Path, cached: Path, *, consent: bool) -> dict:
    require(consent, "explicit-devcontainer-files-consent-required")
    deadline = time.monotonic() + 300
    def check():
        require(time.monotonic() < deadline, "devcontainer-generation-deadline")
    manifest = bundle.cached(cached)
    require(cached.name == manifest["archive"]["sha256"][7:], "verified-bundle-cache-identity")
    require(manifest["target"] == "linux-x86_64", "linux-frontend-bundle-required")
    required = {"bin/latent-dev", "bin/latent-portable-test-host", "helper.pyz", "python-inventory.json",
                "build-provenance.json"}
    require(required <= {entry["path"] for entry in manifest["files"]}, "linux-frontend-bundle-required")
    bundle.verify_cache(cached, manifest, check=check)
    destination = project / ".devcontainer"
    with paths.directory(project):
        require(not destination.exists(), "existing-devcontainer-preserved-merge-manually")
        paths.new_directory(destination)
    nonce = secrets.token_hex(8)
    # This command writes reviewed files only. Image build, network access and
    # container start remain explicit actions in the chosen container toolchain.
    owner = {"schemaVersion": "latent.dev.devcontainer.v1", "nonce": nonce, "sourceCommit": manifest["sourceCommit"],
        "bundleSha256": manifest["archive"]["sha256"], "baseImage": IMAGE, "certificateImage": CERTIFICATE_IMAGE,
        "aptSnapshot": SNAPSHOT,
        "packages": PACKAGES, "volume": "lsf-dev-" + nonce, "state": "preparing",
        "automaticExecution": False, "nodeConnectivity": "explicit-ssh", "qualification": "configuration-only"}
    paths.write_new(destination / "ownership.json", encode(owner))
    verified = destination / "verified"
    paths.new_directory(verified)
    expected = []
    for entry in manifest["files"]:
        path = verified / entry["path"]
        parents = list(path.relative_to(verified).parents)[:-1]
        for parent in reversed(parents):
            folder = verified / parent
            if not folder.exists():
                paths.new_directory(folder)
        copy_verified(cached, entry, path, check=check)
        expected.append(entry["sha256"][7:] + "  " + entry["path"] + "\n")
    paths.write_new(destination / "expected-files.sha256", "".join(expected).encode())
    paths.write_new(destination / "Dockerfile", dockerfile().encode())
    paths.write_new(destination / "devcontainer.json", (json.dumps(configuration(nonce), indent=2) + "\n").encode())
    paths.write_new(destination / ".dockerignore", b"*\n!Dockerfile\n!expected-files.sha256\n!verified/\n!verified/**\n")
    # Every developer generates a fresh ownership nonce and verifies their own
    # selected bundle. Do not share a generated volume identity through Git.
    paths.write_new(destination / ".gitignore", b"/*\n!/.gitignore\n")
    from . import state
    owner["state"] = "prepared"
    state.atomic(destination, "ownership.json", owner)
    return {**owner, "directory": str(destination), "buildStartsContainer": False,
            "next": "Review generated files, then follow the terminal devcontainer guide to build and start."}


def copy_verified(cached: Path, entry: dict, destination: Path, *, check) -> None:
    total, checksum = 0, hashlib.sha256()
    with paths.opened(cached, entry["path"]) as source, paths.directory(destination.parent):
        fd = os.open(destination, os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0), 0o600)
        with os.fdopen(fd, "wb") as output:
            while raw := os.read(source, 1024 * 1024):
                check()
                total += len(raw)
                require(total <= entry["size"], "devcontainer-bundle-changed")
                checksum.update(raw)
                output.write(raw)
            output.flush()
            os.fsync(output.fileno())
    require(total == entry["size"] and "sha256:" + checksum.hexdigest() == entry["sha256"],
            "devcontainer-bundle-changed")
